### ISSUE TITLE
Super Cartoons issues

### ISSUE THREAD

**Issue by sunderlandz** [repoyse/spoyser-repo#39]
Hi Spoyser,

Super Cartoons isn't showing the content.  The only thing I can watch is a short video about the site.

Best regards.

**Comment by chewvodka** [comment]
Agreed.  Looks like the host the streams originate from want you to watch only on their website.

**Comment by repoyse** [comment]
Hosters clearly don't want their site accessed by addon.

**Comment by chewvodka** [comment]
bummer
